apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
  labels:
    tags.datadoghq.com/env: prod
    tags.datadoghq.com/service: spring-boot-app
    tags.datadoghq.com/version: "0.0.1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
        tags.datadoghq.com/env: prod
        tags.datadoghq.com/service: spring-boot-app
        tags.datadoghq.com/version: "0.0.1"
        admission.datadoghq.com/enabled: "true"
      annotations:
        admission.datadoghq.com/java-lib.version: "v1.47.2"
    spec:
      containers:
        - name: spring-boot-app
          image: stkymd/spring-boot-docker:05c18d3
          ports:
            - containerPort: 8080
          env:
            - name: DD_LOGS_INJECTION
              value: "true"
            - name: DD_GIT_COMMIT_SHA
              value: 0cfa2942dde13678fb84733a11c5514259da75a5
            - name: DD_GIT_REPOSITORY_URL
              value: git@github.com:satokiy/dd-demo.git
            - name: DD_ENV
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/env']
            - name: DD_SERVICE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/service']
            - name: DD_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.labels['tags.datadoghq.com/version']
