name: update manifests and create pr
on:
  workflow_dispatch:

jobs:
  update-manifests-and-create-pr:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: update manifests and push feature branch
        run: |
          FULL_COMMIT_SHA=$(git rev-parse HEAD)
          sed -i "s|stkymd/spring-boot-docker:latest|stkymd/spring-boot-docker:$COMMIT_SHA|g" k8s-manifests/deployment.yaml
          sed -i "/DD_GIT_COMMIT_SHA/{n;s|value: .*|value: $FULL_COMMIT_SHA|}" k8s-manifests/deployment.yaml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b feature/$COMMIT_SHA
          git add k8s-manifests/deployment.yaml
          git commit -m "update deployment.yaml"
          git push origin feature/$COMMIT_SHA
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update deployment.yaml"
          title: "update deployment.yaml"
          body: "update deployment.yaml"
          branch: feature/$COMMIT_SHA
          base: "main"