name: build and push docker image
on:
  push:
    branches:
      - main
jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build image
        run: ./gradlew bootBuildImage --imageName=stkymd/spring-boot-docker
      - name: tag image
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          docker tag stkymd/spring-boot-docker:latest stkymd/spring-boot-docker:$COMMIT_SHA
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        run: docker push stkymd/spring-boot-docker:latest

  update-manifests-and-create-pr:
    runs-on: ubuntu-24.04-arm
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: update manifests
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          FULL_COMMIT_SHA=$(git rev-parse HEAD)
          sed -i "s|stkymd/spring-boot-docker:latest|stkymd/spring-boot-docker:$COMMIT_SHA|g" k8s-manifests/deployment.yaml
          sed -i "/DD_GIT_COMMIT_SHA/{n;s|value: .*|value: $FULL_COMMIT_SHA|}" k8s-manifests/deployment.yaml
      - name: create and push feature branch
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b feature/auto-update-manifests
          git add k8s-manifests/deployment.yaml
          git commit -m "update deployment.yaml"
          git push origin feature/auto-update-manifests
      - name: create pull request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "update deployment.yaml"
          title: "update deployment.yaml"
          body: "update deployment.yaml"
          branch: "feature/auto-update-manifests"
          base: "main"