name: build and push docker image
on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!k8s-manifests/**'
jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build image
        run: ./gradlew bootBuildImage --imageName=stkymd/spring-boot-docker
      - name: tag image
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          docker tag stkymd/spring-boot-docker:latest stkymd/spring-boot-docker:$COMMIT_SHA
          docker tag stkymd/spring-boot-docker:latest stkymd/spring-boot-docker:latest
      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push image
        run: |
          docker push stkymd/spring-boot-docker:$COMMIT_SHA  
          docker push stkymd/spring-boot-docker:latest

  update-manifests-and-create-pr:
    runs-on: ubuntu-24.04-arm
    needs: build-and-push
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: update manifests and push feature branch
        run: |
          COMMIT_SHA=$(git rev-parse --short HEAD)
          echo "COMMIT_SHA=$COMMIT_SHA" >> $GITHUB_ENV
          FULL_COMMIT_SHA=$(git rev-parse HEAD)
          sed -i "s|stkymd/spring-boot-docker:[^ ]*|stkymd/spring-boot-docker:$COMMIT_SHA|g" k8s-manifests/deployment.yaml
          sed -i "/DD_GIT_COMMIT_SHA/{n;s|value: .*|value: $FULL_COMMIT_SHA|}" k8s-manifests/deployment.yaml
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b feature/$COMMIT_SHA
          git add k8s-manifests/deployment.yaml
          git commit -m "update deployment.yaml"
          git push origin feature/$COMMIT_SHA
      - name: create pull request
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "update deployment.yaml" \
            --body "This PR updates the deployment.yaml file with the latest Docker image." \
            --head "feature/${{ env.COMMIT_SHA }}" \
            --base "main"